[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {version="1.0.219", features = ["derive"]}
serde_json = "1.0.140"
actix-web = "4"
actix-cors = "0.6.4"
env_logger = "0.10"
